name: Deno CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0
      - name: Install dependencies
        run: npm install
      - name: RUN
        run: echo ${{ secrets.GH_TOKEN }}
      - name: Release
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
